apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
data:
  "accessKey": {{ .Values.global.minio.accessKey | b64enc }}
  "secretKey": {{ .Values.global.minio.secretKey | b64enc }}
  "endpoint": {{ printf "%s-%s" .Release.Name "minio.default.svc.cluster.local:9000" | b64enc }}
