apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
data:
  "username": {{ .Values.global.rabbitmq.username | b64enc }}
  "password": {{ .Values.global.rabbitmq.password | b64enc }}
  "address": {{ printf "%s-%s" .Release.Name "rabbitmq.default.svc.cluster.local" | b64enc }}
