sudo: required
language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt

script:
- flake8 --max-line-length=100 src/
- flake8 --max-line-length=100 tests/
- python -m pytest -v tests/

notifications:
email: false
