apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: {{ .Values.image }}:{{ .Values.tag }}
        command:
        - dispatcher
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
        - name: RABBITMQ_ADDR
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: address
