# based on https://github.com/gavinzhou/ci-minikube
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K8S_VERSION: v1.10.0
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.29.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
    - checkout
    - run:
        name: setup kubectl
        command: |
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          mkdir -p ${HOME}/.kube
          touch ${HOME}/.kube/config
    - run:
        name: setup minikube
        command: |
          curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
    - run:
        name: setup helm
        command: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
    - run:
        name: start minikube
        command: |
          sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048 --kubernetes-version=${K8S_VERSION} &> $HOME/minikube.log 2>&1 < /dev/null
    - run:
        name: wait for minikube
        command: |
          JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
          until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
            sleep 1;
          done
    - run:
        name: fix RBAC
        command: |
          # make default account cluster-admin
          kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
    - run:
        name: dump cluster-info
        command: |
          kubectl cluster-info
          kubectl get po --all-namespaces
    - run:
        name: install helm in cluster
        command: |
          kubectl -n kube-system create sa tiller
          kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
          helm init --wait --service-account tiller
  style_check:
    docker:
    - image: circleci/python:3.6.6-jessie-browsers
    working_directory: ~/scrap-me
    steps:
    - checkout
    - run:
        name: create venv, install flake8, run flake8
        command: |
          python3 -m venv .venv
          . ~/scrap-me/.venv/bin/activate
          pip install -q flake8
          echo "Test src catalog: " && flake8 --ignore=W605 --max-line-length=100 src/
          echo "Test tests catalog: " && flake8 --ignore=W605 --max-line-length=100 tests/
  tests:
    docker:
    - image: circleci/python:3.6.6-jessie-browsers
    working_directory: ~/scrap-me
    steps:
    - checkout
    - run:
        name: run pytest
        command: |
          python3 -m venv .venv
          . ~/scrap-me/.venv/bin/activate
          pip install -q -r requirements.txt
          pytest -v tests/
workflows:
  version: 2
  create_environment:
    jobs:
      - build
      - style_check
      - tests
