version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-jessie-browsers
    working_directory: ~/scrap-me
    steps:
      - checkout
      - run:
          name: create venv, install flake8
          command: |
            python3 -m venv .venv
            . ~/scrap-me/.venv/bin/activate
            pip install -q flake8
      - run:
          name: run style check
          command: |
            . ~/scrap-me/.venv/bin/activate
            echo "Test src catalog: " && flake8 src/
            echo "Test tests catalog: " && flake8 tests/
      - run:
          name: run tests
          command: |
            . ~/scrap-me/.venv/bin/activate
            pytest -v tests/
  environment:
    machine: true
    environment:
      MINIKUBE_WANTUPDATENOTIFICATION=false
      MINIKUBE_WANTREPORTERRORPROMPT=false
      MINIKUBE_HOME=$HOME
      CHANGE_MINIKUBE_NONE_USER=true
      KUBECONFIG=$HOME/.kube/config
    steps:
      - checkout
      - run:
          name: install minikube and kubectl
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo cp kubectl /usr/local/bin/ && rm kubectl
            mkdir -p $HOME/.kube
            mkdir -p $HOME/.minikube
            touch $HOME/.kube/config
            sudo -E minikube start --vm-driver=none
            for i in {1..150}; do
              kubectl get po &> /dev/null
              if [ $? -ne 1 ]; then
                break
              fi
              sleep 2
            done
      - run:
          name: fix RBAC
          command: |
            # make default account cluster-admin
            kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
      - run:
          name: install helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: set up k8s for helm
          command: |
            kubectl create serviceaccount --namespace kube-system tiller
            kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
            helm init --wait --service-account tiller
workflows:
  version: 2
  create_environment:
    jobs:
      - build
      - environment
